
openapi: 3.0.3
info:
  contact:
    email: info@inss.ch
    name: Oliver Glas
    url: http://inss.ch
  description: Sample API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  title: Sample with one POST and one GET.
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: The local host.
  variables:
    port:
      enum:
        - '8080'
      default: '8080'
tags:
- description: Just sample methods.
  name: sample
paths:
  /sample:
    post:
      description: Create a sample object.
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      responses:
        "201":
         description: Sample created
        "400":
          description: Sample exists already. Choose another name.
        "405":
          description: Invalid input.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Sample for a POST.
      tags:
      - sample
  /sample/validate/{sampleId}:
    get:
      description: Sample 
      operationId: getById
      parameters:
      - description: The id of the sample
        explode: false
        in: path
        name: sampleId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleObject'
          description: Validation result
        "400":
          description: Invalid ID
        "404":
          description: Sample not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: The GET sample
      tags:
      - sample
components:
  schemas:
    Sample:
      required:
      - name
      properties:
        name:
          example: 'Sample'
          type: string
        filename:
          example: Sample.txt
          type: string
        version:
          example: 0.0.1
          type: string

    SampleObject:
      required:
      - id
      properties:
        id:
          description: The ID of the object.
          type: string
          example: '1'
        sample1:
          description: Sample one
          type: string
          example: 'one'
        sample2:
          description: Sample two
          type: string
          example: 'two'
        sample3:
          description: Sample three
          type: string
          example: 'three'
    Error:
      properties:
        code:
          example: 404
          format: int32
          type: integer
        message:
          example: Unexpected error.
          type: string
      required:
      - code
      - message
